/**
 * @file VoiceManager.cpp
 * @brief Implementation of polyphony and envelopes handling
 * 
 * @author Lilith Estévez Boeta
 * @date 2026-04-28
 */

#include "VoiceManager.hpp"

/**
 * @brief Default Envelope constructor initializing ADSR states 
 * 
 * @details Defaults the envelope to attack=0.1, decay=0.1, 
 * sustain=0.7 and release=0.2 with phase set as OFF.
 * 
 * @ingroup voice_module
 */
Envelope::Envelope() : state(ADSRState::OFF), attackTime(0.1f), decayTime(0.1f), sustainLevel(0.7f), releaseTime(0.2f), currentAmplitude(0.0f), currentTime(0.0f), lastAmplitude(0.0f) {}

/**
 * @brief Custom Envelope constructor setting explicit ADSR phases
 * 
 * @details This initializes a complete envelope ready for activation.
 * The envelope is initialized sequentially avoiding transient noises.
 * 
 * @ingroup voice_module
 * 
 * @param[in] attack Length of attack climb phase (seconds) 
 * @param[in] decay Length of decay descent phase (seconds)
 * @param[in] sustain Value of holding level threshold
 * @param[in] release Length of fade-out tracking phase (seconds)
 */
Envelope::Envelope(float attack, float decay, float sustain, float release) : state(ADSRState::OFF), attackTime(attack), decayTime(decay), sustainLevel(sustain), releaseTime(release), currentAmplitude(0.0f), currentTime(0.0f), lastAmplitude(0.0f) {}

/**
 * @brief Drives state machine yielding sequential phase amplitudes
 * 
 * @details Evaluates the local phase timestamp compared to configured ADSR 
 * parameters. State changes sequentially. Returns current calculated sample.
 * 
 * @ingroup voice_module
 * 
 * @param[in] deltaTime The fraction of a second passed since last call
 * @return Latest computed amplitude multiplier coefficient
 * @retval 0.0 Phase is OFF
 */
float	Envelope::nextAmplitude(float deltaTime)
{
	switch (state)
	{
		case ADSRState::ATTACK:
			currentAmplitude += deltaTime / attackTime;
			currentTime += deltaTime;
			if (currentTime >= attackTime)
			{
				currentAmplitude = 1.0f;
				state = ADSRState::DECAY;
				currentTime = 0.0f;
			}
			break;
		case ADSRState::DECAY:
			currentAmplitude -= deltaTime * (1.0f - sustainLevel) / decayTime;
			currentTime += deltaTime;
			if (currentTime >= decayTime)
			{
				currentAmplitude = sustainLevel;
				state = ADSRState::SUSTAIN;
				currentTime = 0.0f;
			}
			break;
		case ADSRState::RELEASE:
			currentAmplitude -= deltaTime * lastAmplitude / releaseTime;
			currentTime += deltaTime;
			if (currentTime >= releaseTime)
			{
				currentAmplitude = 0.0f;
				lastAmplitude = currentAmplitude;
				state = ADSRState::OFF;
				currentTime = 0.0f;
			}
			break;
		default:
			break;
	}
	return currentAmplitude;
}

/**
 * @brief Activates the envelope beginning Attack phase 
 * 
 * @details Resets envelope clocks and places state in ATTACK to simulate
 * an engaged synthetic press action.
 * 
 * @ingroup voice_module
 */
void	Envelope::start()
{
	state = ADSRState::ATTACK;
	currentTime = 0.0f;
	currentAmplitude = 0.0f;
	lastAmplitude = 0.0f;
}

/**
 * @brief Calculates combined single sample generated by SynthVoice 
 * 
 * @details Applies modulator to carrier generation logic alongside
 * velocity scale and current dynamic ADSR generation output multiplier.
 * 
 * @ingroup voice_module
 * 
 * @return Latest computed amplitude sample floating point waveform sum
 */
float	SynthVoice::nextSample() { return carrier.nextSample(modulator.nextSample() * modulationIndex) * env.nextAmplitude(1.0f / 44100.0f) * velocity; }

/**
 * @brief Activates the specific synthesizer voice
 * 
 * @details Takes absolute synthesis properties (note, frequency, tuning) 
 * alongside FM routing (Modulator scale factors parameterization). Starts
 * ADSR playback.
 * 
 * @ingroup voice_module
 * 
 * @param[in] midiNote Assigned base note identifier
 * @param[in] modulationIndex Scalar modifier dictating intensity
 * @param[in] modulationRatio Ratio affecting modulator oscillator 
 * @param[in] frequency Target absolute carrier hz frequency
 * @param[in] velocity Impact variable scaling overall strength
 * @param[in] sampleRate Frequency rate used to calibrate Oscillators
 * @param[in] waveform Selectable synthesis type
 */
void	SynthVoice::noteOn(int midiNote, float modulationIndex, float modulationRatio, float frequency, float velocity, float sampleRate, Waveform waveform)
{
	this->midiNote = midiNote;
	this->velocity = velocity;
	carrier = Oscilator(frequency, sampleRate, waveform);
	modulator = Oscilator(frequency * modulationRatio, sampleRate, Waveform::SINE);
	this->modulationIndex = modulationIndex;
	env.start();
}

/**
 * @brief Deactivates the specific synthesizer voice
 * 
 * @details Commands the ADSR component into phase RELEASE enabling gradual
 * fade-out attenuation of volume.
 * 
 * @ingroup voice_module
 */
void	SynthVoice::noteOff() { env.state = ADSRState::RELEASE; env.currentTime = 0.0f; env.lastAmplitude = env.currentAmplitude; }

/**
 * @brief Default VoiceManager constructor 
 * 
 * @details Establishes polyphony base properties at 8 voices maximum.
 * 
 * @ingroup voice_module
 */
VoiceManager::VoiceManager() : maxVoices(8), sampleRate(44100.0f) { voices.resize(maxVoices); }

/**
 * @brief Parameterized VoiceManager configuration setup 
 * 
 * @details Resizes the primary vector to hold provided polyphonic limit
 * allocations tracking sample rates.
 * 
 * @ingroup voice_module
 * 
 * @param[in] maxVoices Polyphonic voices boundary limitation limit
 * @param[in] sampleRate Sample generation system frequency
 */
VoiceManager::VoiceManager(int maxVoices, float sampleRate) : maxVoices(maxVoices), sampleRate(sampleRate) { voices.resize(maxVoices); }

/**
 * @brief Assigns an idle synth voice or overrides oldest playing voice 
 * 
 * @details Searches for completely available inactive (OFF) configurations
 * before searching for those experiencing a releasing fade. If all are 
 * occupied, overrides oldest running active allocation unconditionally.
 * 
 * @ingroup voice_module
 * 
 * @param[in] midiNote Number identifying incoming key command
 * @param[in] modulationIndex FM algorithmic intensity setting
 * @param[in] modulationRatio Relationship frequency parameter 
 * @param[in] frequency Raw playback note target (in Hz)
 * @param[in] velocity Scaling attribute of loudness
 * @param[in] waveform Initial shape for generation calculation
 */
void	VoiceManager::noteOn(int midiNote, float modulationIndex, float modulationRatio, float frequency, float velocity, Waveform waveform)
{
	for (int i = 0; i < maxVoices; i++)
	{
		if (voices[i].env.state == ADSRState::OFF)
		{
			voices[i].noteOn(midiNote, modulationIndex, modulationRatio, frequency, velocity, sampleRate, waveform);
			return;
		}
	}

	int		oldestVoiceIndex = 0;
	float	maxTime = -1.0f;
	for (int i = 0; i < maxVoices; i++)
	{
		if (voices[i].env.state == ADSRState::RELEASE)
		{
			oldestVoiceIndex = i;
			break;
		}
		if (voices[i].env.currentTime > maxTime)
		{
			maxTime = voices[i].env.currentTime;
			oldestVoiceIndex = i;
		}
	}
	voices[oldestVoiceIndex].noteOn(midiNote, modulationIndex, modulationRatio, frequency, velocity, sampleRate, waveform);
}

/**
 * @brief Signals termination of an actively synthesized note
 * 
 * @details Finds all actively playing synthesizer voices connected to
 * the passed note mapping number and forces their envelopes into
 * the decay release phase.
 * 
 * @ingroup voice_module
 * 
 * @param[in] midiNote Specific identifying tracked MIDI key 
 */
void	VoiceManager::noteOff(int midiNote)
{
	for (int i = 0; i < maxVoices; i++)
		if (voices[i].midiNote == midiNote && (voices[i].env.state != ADSRState::OFF && voices[i].env.state != ADSRState::RELEASE))
			voices[i].noteOff();
}

/**
 * @brief Produces a single mixed sample of audio 
 * 
 * @details Traverses internal Voice array pulling next generation outputs
 * representing polyphonic sounds.
 * 
 * @ingroup voice_module
 * 
 * @return Scaled aggregation of active envelope results
 */
float	VoiceManager::nextSample()
{
	float	sample = 0.0f;

	for (int i = 0; i < maxVoices; ++i)
		if (voices[i].env.state != ADSRState::OFF)
			sample += voices[i].nextSample();

	return sample / maxVoices;
}
